### ISSUE TITLE
Installation fails on linux

### ISSUE THREAD

**Issue by stuartm** [coherence-project/UPnP-Inspector#1]
# easy_install upnp-inspector

Searching for upnp-inspector
Best match: UPnP-Inspector 0.2.3
Processing UPnP_Inspector-0.2.3-py2.7.egg
UPnP-Inspector 0.2.3 is already the active version in easy-install.pth
Installing upnp-inspector script to /usr/bin

Using /usr/lib/python2.7/site-packages/UPnP_Inspector-0.2.3-py2.7.egg
Processing dependencies for upnp-inspector
Searching for pygtk
Reading https://pypi.python.org/simple/pygtk/
Reading http://ftp.acc.umu.se/pub/gnome/binaries/win32/pygtk/2.24/
Reading http://www.daa.com.au/~james/pygtk/
Reading http://www.daa.com.au/~james/software/pygtk/
Reading http://www.pygtk.org
Reading http://www.pygtk.org/
Best match: pygtk 2.24.0
Downloading https://pypi.python.org/packages/source/P/PyGTK/pygtk-2.24.0.tar.bz2#md5=a1051d5794fd7696d3c1af6422d17a49
Processing pygtk-2.24.0.tar.bz2
Writing /tmp/easy_install-MEBnJ6/pygtk-2.24.0/setup.cfg
Running pygtk-2.24.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-MEBnJ6/pygtk-2.24.0/egg-dist-tmp-maogOV
error: Setup script exited with ********************************************************************
- Building PyGTK using distutils is only supported on windows. *
- To build PyGTK in a supported way, read the INSTALL file.    *
  ********************************************************************

**Comment by htgoebel** [comment]
As it seams, PyGTK is not meant to be installed using distutils/easy_install/pip. Please use the pygtk package your Linux distribution provides.

**Comment by stuartm** [comment]
You're right, it seems to be a bug with easy_install because pygtk is already installed.

I guess I'll have to install upnp-inspector by hand.

**Comment by htgoebel** [comment]
As a work-around you could remove the requirement for pygtk from setup.py.

**Comment by alexwilliamsdr** [comment]
I tried that (removed pygtk from setup.py,) but instead of encountering that issue, I got something else:
Adding Twisted 17.9.0 to easy-install.pth file
Installing trial script to /usr/bin
Installing conch script to /usr/bin
Installing ckeygen script to /usr/bin
Installing twist script to /usr/bin
Installing pyhtmlizer script to /usr/bin
Installing mailmail script to /usr/bin
Installing tkconch script to /usr/bin
Installing twistd script to /usr/bin
Installing cftp script to /usr/bin

Installed /usr/lib/python2.7/site-packages/Twisted-17.9.0-py2.7-linux-x86_64.egg
Searching for Coherence>=0.6.4
**Reading https://pypi.python.org/simple/Coherence/
No local packages or download links found for Coherence>=0.6.4
error: Could not find suitable distribution for Requirement.parse('Coherence>=0.6.4')**

**Comment by htgoebel** [comment]
The PyPI entries are unmaintained and the account-owner vanished. Please install Coherence manually:
```
pip install https://github.com/coherence-project/Coherence/archive/Coherence-0.6.6.2.tar.gz
```
